"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.updateUserById = exports.deleteUserById = exports.createUser = exports.getUserById = exports.getUserBySessionToken = exports.getUserByEmail = exports.getUsers = void 0;
const users_1 = require("../models/users");
const getUsers = () => users_1.UserModel.find();
exports.getUsers = getUsers;
const getUserByEmail = (email) => users_1.UserModel.findOne({ email });
exports.getUserByEmail = getUserByEmail;
const getUserBySessionToken = (sessionToken) => users_1.UserModel.findOne({ 'authentication.sessionToken': sessionToken });
exports.getUserBySessionToken = getUserBySessionToken;
const getUserById = (id) => users_1.UserModel.findById(id);
exports.getUserById = getUserById;
const createUser = (values) => new users_1.UserModel(values).save().then((user) => user.toObject());
exports.createUser = createUser;
const deleteUserById = (id) => users_1.UserModel.findOneAndDelete({ _id: id });
exports.deleteUserById = deleteUserById;
const updateUserById = (id, values) => users_1.UserModel.findByIdAndUpdate(id, values);
exports.updateUserById = updateUserById;
