import Sidebar from "@/components/ui/sidebar";
import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import { getServerSession } from "next-auth";
import { Inter as FontSans } from "next/font/google";
import { redirect } from "next/navigation";

export const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();

  if (!session) {
    redirect("/auth");
  }

  return (
    <main
      className={cn(
        "min-h-screen bg-background overflow-x-hidden font-sans antialiased flex",
        fontSans.variable
      )}
    >
      <Sidebar />
      <section className="flex-1">{children}</section>
    </main>
  );
}
